# Site settings
title:         mek's notepad
tagline:       embedded and linux notes
email:         mek.xgt@gmail.com
url:           "http://mek-x.github.io"
description:   Embedded systems and Linux enthusiast notepad
baseurl:       ""


author:
  name:        "Kamil Wcislo"
  url:         "http://mek-x.github.io"

paginate: 5


github_username:  mek-x


# Build settings
markdown:     kramdown
highlighter:  pygments
