# Site settings
title:         mek's notepad
tagline:       embedded linux
url:           "http://mek-x.github.io"
description:   Embedded systems and Linux enthusiast's notepad
baseurl:       ""

author:
  name:        "Kamil Wcislo"
  url:         "http://mek-x.github.io"

# github
github_username:  mek-x


# Build settings
markdown:     kramdown
highlighter:  pygments
paginate:     5
